---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-added-large-files
    - id: check-symlinks

# this is a fun tool that detects secrets (tokens, etc.)
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
    - id: detect-secrets
