ARG IMAGE_NAME=node
ARG IMAGE_TAG=16
ARG APPHOME=/usr/src/app
ARG HOST=0.0.0.0
ARG PORT=3000
ARG NODE_ENVIRONMENT=production
ARG RUNNER=runner

FROM ${IMAGE_NAME}:${IMAGE_TAG}

ARG IMAGE_NAME
ARG IMAGE_TAG
ARG APPHOME
ARG HOST
ARG PORT
ARG NODE_ENVIRONMENT
ARG RUNNER

RUN mkdir -p ${APPHOME}

WORKDIR ${APPHOME}

RUN getent passwd "${RUNNER}" > /dev/null \
    || adduser ${RUNNER} \
    && chown -R ${RUNNER} ${APPHOME}


USER ${RUNNER}

COPY . ${APPHOME}

RUN npm set unsafe-perm true \
  && npm install

ENV NODE_ENV=${NODE_ENVIRONMENT}

COPY . ${APPHOME}

RUN npm run build

ENV HOST=${HOST}
EXPOSE ${PORT}
ENV NUXT_HOST=${HOST}
ENV NUXT_PORT=${PORT}

CMD ["npm", "run", "dev"]
