export const featurePolicy = [
  "accelerometer 'none'",
  "ambient-light-sensor 'none'",
  "autoplay 'none'",
  "battery 'none'",
  "camera 'none'",
  "display-capture 'none'",
  "document-domain 'none'",
  "encrypted-media 'none'",
  "fullscreen 'none'",
  "geolocation 'none'",
  "gyroscope 'none'",
  "magnetometer 'none'",
  "microphone 'none'",
  "midi 'none'",
  "navigation-override 'none'",
  "payment 'none'",
  "picture-in-picture 'none'",
  "publickey-credentials-get 'none'",
  "usb 'none'",
  "wake-lock 'none'",
  "screen-wake-lock 'none'",
  "web-share 'none'",
  "xr-spatial-tracking 'none'",
];
