---
name: Deploy

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - release
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Test frontend
        run: npm run test
