---
name: Deploy

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:  
    
  pull_request:
    branches:      
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.merged == true

    # only deploy when a PR is merged
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Wait for checks to pass
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'test frontend'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Deploy frontend to Federalist
        run: npm run federalist:local
