---
name: OWASP ZAP Baseline Scan

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:

jobs:
  ZAP:
    name: OWASP ZAP Baseline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          # yamllint disable-line rule:line-length
          target: 'https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/'
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a -n .zap/context.txt"
