---
name: pa11y tests

# yamllint disable-line rule:truthy
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci && npm install pa11y pa11y-ci

      - name: Build the site
        run: npm run build && npx nuxt generate

      - name: Run pa11y test
        uses: booleans-oss/pa11y-actions@v1
        with:
          start: "dev"
          port: 3000
