---
name: Semgrep

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # Scan changed files in PRs, block on new issues
  # only (existing issues ignored)
  push:

  # Scan all files on branches, block on any issues
  # push:
  #   branches: ["master", "main"]

  # Schedule this job to run at a certain time,
  # using cron syntax
  #
  # Note that * is a special character in YAML
  # so you have to quote this string
  # schedule:
  #   - cron: '30 0 1,15 * *'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    container:
      image: returntocorp/semgrep
    steps:
      # Fetch project source
      - uses: actions/checkout@v3
      - run: semgrep scan --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >- # more at semgrep.dev/r
            p/security-audit
            p/secrets

      - name: Check to see if the SARIF a was generated
        id: sarif_file_exists
        uses: andstor/file-existence-action@v1
        with:
          files: "semgrep.sarif"

      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v1
        if: steps.sarif_file_exists.outputs.files_exists == 'true'
        with:
          sarif_file: semgrep.sarif
