---
name: Semgrep

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # Scan changed files in PRs, block on new issues
  # only (existing issues ignored)
  push:

  # Scan all files on branches, block on any issues
  # push:
  #   branches: ["master", "main"]

  # Schedule this job to run at a certain time,
  # using cron syntax
  #
  # Note that * is a special character in YAML
  # so you have to quote this string
  # schedule:
  #   - cron: '30 0 1,15 * *'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v2

      - uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "1"
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets

      # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      - uses: github/codeql-action/upload-sarif@v1
        name: Upload SARIF file for GitHub Advanced Security Dashboard
        with:
          sarif_file: semgrep.sarif
        if: always()
